services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=tools
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: api
    image: bossabox-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db:

